name: "Publish to Maven"
description: |
  A subcomponent of pulumi-package-publish

inputs:
  version:
    description: The version of the provider being published.
    required: true
  gradle-version:
    description: The version of gradle to use.
    default: 7.4.1

runs:
  using: "composite"
  steps:
    - name: Download java SDK
      uses: actions/download-artifact@v8
      with:
        name: java-sdk.tar.gz
        path: ${{ github.workspace}}/sdk/
    - name: Uncompress java SDK
      run: mkdir -p ${{ github.workspace }}/sdk/java && tar -zxf ${{github.workspace}}/sdk/java.tar.gz -C
        ${{github.workspace}}/sdk/java
      shell: bash
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2
      with:
        gradle-version: ${{ inputs.gradle-version }}
    - name: Publish Java SDK
      continue-on-error: true
      shell: bash
      working-directory: ./sdk/java
      env:
        PACKAGE_VERSION: ${{ inputs.version }}
      run: gradle publishToSonatype closeAndReleaseSonatypeStagingRepository
