name: 'Publish to Maven'
description: |
  A subcomponent of pulumi-package-publish

inputs:
  version:
    description: The version of the provider being published.
    required: true

runs:
  using: "composite"
  steps:
    - name: Download java SDK
      uses: actions/download-artifact@v4
      with:
        name: java-sdk.tar.gz
        path: ${{ github.workspace}}/sdk/
    - name: Uncompress java SDK
      run: tar -zxf ${{github.workspace}}/sdk/java.tar.gz -C
        ${{github.workspace}}/sdk/java
      shell: bash
    - name: Publish Java SDK
      continue-on-error: true
      uses: gradle/gradle-build-action@9b814496b50909128c6a52622b416c5ffa04db49
      env:
        PACKAGE_VERSION: ${{ inputs.version }}
      with:
        arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository
        build-root-directory: ./sdk/java
        gradle-version: 7.4.1
