name: 'Pulumi Package publisher'
description: 'A GitHub Action that publishes provider SDKs'
inputs:
  sdk:
    description: |
      The name of the language SDK being published.

      To enable a single language, specify that language:

          sdk: nodejs

      To enable multiple languages, specify them:

          sdk: nodejs,python

      To enable all languages (the default), specify 'all':

          sdk: all

      To disable only a single language (but enable all others), use:

          sdk: all,!nodejs

    required: false
    default: 'all'

# The if: statement for the above is:
#
# if: (contains(inputs.sdk, '${LANGUAGE}') || (contains(inputs.sdk, 'all') && !contains(inputs.sdk, '!all'))) && !contains(inputs.sdk, '!${LANGUAGE}')
#
# If can be read as:
#
#    If (${LANGUAGE} or all (but not !all)) and not !${LANGUAGE}

runs:
  using: "composite"
  steps:
    - name: Verify input
      run: echo 'Publishing SDK:' && echo ${{ inputs.sdk }}
      shell: bash
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}
    - name: Unshallow clone for tags
      run: git fetch --prune --unshallow --tags
      shell: bash
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GOVERSION }}
    - name: Install pulumictl
      uses: jaxxstorm/action-install-gh-release@v1.5.0
      with:
        repo: pulumi/pulumictl
    - name: Install Pulumi CLI
      uses: pulumi/action-install-pulumi-cli@v2


    # `uses:` statements do not support expressions
    # (https://github.com/actions/runner/issues/895), so this is invalid:
    #
    #   ${{ github.action_path }}/langs
    #
    # This is a problem for nested composite actions, which are unable to specify a
    # `uses:` relative to the main composite action.
    #
    # While they need to be static, they do not need to be resolved. We can work around
    # the static requirement by specifying a local static path in downstream `uses:`, and
    # then moving the desired action to the static path at runtime.
    - name: Setup Language Workflows
      run: |
        mkdir -p ./.pulumi-package-publish/langs
        cp -r ${{ github.action_path }}/langs ./.pulumi-package-publish/langs
      shell: bash

    - name: Nodejs - Publish to NPM
      uses: ./.pulumi-package-publish/langs/langs/nodejs.yml
      if: (contains(inputs.sdk, 'nodejs') || (contains(inputs.sdk, 'all') && !contains(inputs.sdk, '!all'))) && !contains(inputs.sdk, '!nodejs')
    - name: .NET - Publish to Nuget
      if: (contains(inputs.sdk, 'dotnet') || (contains(inputs.sdk, 'all') && !contains(inputs.sdk, '!all'))) && !contains(inputs.sdk, '!dotnet')
      uses: ./.pulumi-package-publish/langs/langs/dotnet.yml
    - name: Python - Publish to PyPi
      if: (contains(inputs.sdk, 'python') || (contains(inputs.sdk, 'all') && !contains(inputs.sdk, '!all'))) && !contains(inputs.sdk, '!python')
      uses: ./.pulumi-package-publish/langs/langs/python.yml
    - name: Java - Publish to Maven
      if: (contains(inputs.sdk, 'java') || (contains(inputs.sdk, 'all') && !contains(inputs.sdk, '!all'))) && !contains(inputs.sdk, '!java')
      uses: ./.pulumi-package-publish/langs/langs/java.yml
