name: 'Publish to Nuget'
description: |
  A subcomponent of pulumi-package-publish

inputs:
  version:
    description: >-
      The version of the provider being published.

      TODO: Validate that the SDK we are publishing matches this input.
    required: true

runs:
  using: "composite"
  steps:
    - name: Download dotnet SDK
      uses: actions/download-artifact@v4
      with:
        name: dotnet-sdk.tar.gz
        path: ${{ github.workspace }}/sdk/
    - name: Uncompress dotnet SDK
      run: tar -zxf ${{ github.workspace }}/sdk/dotnet.tar.gz -C
        ${{ github.workspace }}/sdk/dotnet
      shell: bash
    - name: Publish dotnet SDK
      run: find "${{ github.workspace }}/sdk/dotnet/bin/Debug/" -name '*.nupkg' -print0 |
        xargs -0 -I {} dotnet nuget push -k "${NUGET_PUBLISH_KEY}" -s https://api.nuget.org/v3/index.json --skip-duplicate {}
      shell: bash
